# Generated by Django 3.2.6 on 2021-08-23 21:59

from django.db import migrations, models
import face_recognition_rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=face_recognition_rest.models.Picture.get_upload_path),
        ),
    ]
